In [95]:
import math
import numpy as np

def segmoid(x):  # Segmoid is manily used to return binary values either 0 or 1 for continuous values ..
    return 1/(1+math.exp(-x))

dp1={'no':100,'maxtemp':35,'mintemp':35,'maxvibration':12, 'aspierity':0.32}
dp2={'no':100,'maxtemp':46,'mintemp':35,'maxvibration':21, 'aspierity':0.34}
dp3={'no':100,'maxtemp':56,'mintemp':46,'maxvibration':3412,'aspierity':12.42}
dp4={'no':100,'maxtemp':58,'mintemp':48,'maxvibration':3542,'aspierity':13.43}

x1=[v for k,v in dp1.items()][2:4]+[v for k,v in dp1.items()][0:1]

# we have to add 1 to the begining of the x vector to support the bias
x1=[1]+[v for k,v in dp1.items()][2:4]+[v for k,v in dp1.items()][0:1]
x2=[1]+[v for k,v in dp1.items()][2:4]+[v for k,v in dp2.items()][0:1]
x3=[1]+[v for k,v in dp1.items()][2:4]+[v for k,v in dp3.items()][0:1]
x4=[1]+[v for k,v in dp1.items()][2:4]+[v for k,v in dp4.items()][0:1]
print("Sliced elements are:"+str(x1))

# native python arrays are slow and also will not support linear algebra operations 
x1=np.array(x1)
x2=np.array(x2)
x3=np.array(x3)
x4=np.array(x4)
print("Numpy array is:"+str(x1))

#w_layer1=np.random.rand(4) # this is a vector 
w_layer1=np.random.rand(4,4) # this is a matrix 
print("random weight vector for layer1 is:"+str(w_layer1))
def segmoid(x):
    return 1/(1+np.exp(-x))
def layer1(x):
    return segmoid(x.dot(w_layer1)) # segmoid will be useful to tell the values between 0 and 1

dataset=np.array([x1,x2,x3,x4])

firstlayer_result=layer1(dataset) # here we will not get any useful result as we have not trained weight vector and as we put random values for weight vector

print("Layer 1:"+str(firstlayer_result))
w_layer2=np.random.rand(4,4) # this is a matrix 

def layer2(x):
    return segmoid(x.dot(w_layer1)) # segmoid will be useful to tell the values between 0 and 1

print("Layer 2:"+str(layer2(firstlayer_result)))


Sliced elements are:[1, 12, 35, 35]
Numpy array is:[ 1 12 35 35]
random weight vector for layer1 is:[[ 0.79117754  0.35911795  0.06491095  0.30570424]
 [ 0.42124724  0.21819125  0.76667879  0.82949402]
 [ 0.89592676  0.61672662  0.59740269  0.09185441]
 [ 0.05290295  0.19794273  0.90465027  0.44182223]]
Layer 1:[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
Layer 2:[[ 0.89671579  0.80090792  0.91162525  0.84142576]
 [ 0.89671579  0.80090792  0.91162525  0.84142576]
 [ 0.89671579  0.80090792  0.91162525  0.84142576]
 [ 0.89671579  0.80090792  0.91162525  0.84142576]]
